---
title: "Discussion"
author: "Chris Guo"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
output: word_document
bibliography: "`r file.path(here::here(), 'doc.ignore', 'nfaa_references.bib')`"
csl: "`r file.path(here::here(), 'doc.ignore', 'ecology.csl')`"
link-citations: true
---

```{r include=FALSE}
library(knitr)
```

### Salmonids

#### Pacific salmon

Interest in Pacific salmon (*Oncorhynchus spp.*) use of nearshore habitats comes from a need to better understand early life stages when they transition from fresh to marine habitats (outmigration) that coincides with a physiological transition (smoltification) requiring increased foraging to meet metabolic demands [@McCormick.Saunders.1987]. Outmigration happens in spring and early summer, but timing of recruitment into the nearshore and residence periods vary among species and populations [@Orsi.etal.2000; @Olsen.etal.2003; @Moore.etal.2016]. In general, pink (*O. gorbuscha*) and chum (*O. keta*) move into the nearshore earliest as YOY [@Jaenicke.etal.1985], but chinook (*O. tshawytscha*), sockeye (*O. nerka*), and coho (*O. kisutch*) can spend multiple years in freshwater habitats before outmigration [@Moulton.etal.1997]. However, some populations exhibit variable nearshore and estuarine habitat usage between rearing years [@Powers.etal.2007], often migrating among transitional waterways like saltmarshes, eelgrass, and river-adjacent beaches [@Koski.2009; @Hoem-Neher.etal.2013; @MarinJarrin.Miller.2013]. Juvenile salmon differ in their spatial distributions as well [@Farley.etal.2005], relating to environmental factors that can be scale-dependent (e.g., natal watershed size, regional climate regime, local hydrological conditions) and that vary among species, population, or sub-population levels [@Olsen.etal.2003; @Hart.2023]. During nearshore residency, juvenile salmon can dominate community assemblages making them potentially important forage species [@Springer.etal.1997]. Release of hatchery stocks can affect their role as prey [@Malick.etal.2009; @Duncan.2018], and additionally may alter inter-community dynamics with wild stocks of the same species, another salmon species, or other community members [@Murphy.etal.1988; @Orsi.etal.2004; @Wessel.2004; @Blikshteyn.2005; @LaCroix.etal.2009; @Moss.etal.2009]. Nearshore residence is seen as critical in terms of marine mortality, where juvenile energy and growth may have positive relationships with spawner recruitment and adult success [@Linley.2001; @Powers.etal.2006; @Malick.etal.2009]. But, limited means to track populations in the open ocean makes the exact impact of the nearshore difficult to discern from influences in the pelagic ecosystem [c.f., @Yasumiishi.etal.2016; @Deeg.etal.2025].

@Farley.etal.2007

#### Dolly Varden

Dolly Varden (*Salvelinus malma*) are iteroparous, facultative (vs obligate) anadromous

### Groundfishes

Groundfish research was heavily pursued in the 1990s resulting from a regime shift in the North Pacific dating back to the late 1970s when the PDO made a negative-to-positive switch [@Litzow.2006]. During this period (ca. 1976-1999), marine biomass concentrations moved from mid-trophic crustaceans (shrimp and crab) and pelagic forage species (capelin and herring) to upper-trophic demersal preators [@Francis.etal.1998; @Anderson.Piatt.1999]. Big winners of the regime shift were gadids (*Gadidae*) and flatfishes (*Pleuronectidae*), becoming some of the largest commercial fisheries in the state by the late 90s [@Clarke.etal.1999; @Bailey.2000]. Similar to Pacific salmon research, groundfish studies sought to better understand growth, energetics, and recruitment to adult populations in these emergent fisheries, which led to research on juvenile life stages in the nearshore [@Norcross.etal.1997; @Abookire.etal.2001; @Doyle.Mier.2016].

#### Gadids

Pacific cod (*Gadus macrocephalus*) and walleye pollock (*G. chalcogrammus*) represent important fisheries in the Gulf of Alaska and southeastern Bering Sea, where nearshore-related research has developed a good understanding of nursery function on these gadids [@Bailer.etal.1996; @Siddon.2013; @Gruss.etal.2021; @Abookire.etal.2024]. Arctic cod (*Boreogadus saida*) has received interest in the Beaufort and Chukchi Seas but more so from a trophic and ecosystem perspective [@Craig.1984; @Therdinga.etal.2013]. Saffron cod (*Eleginus gracilis*) co-occur in nearshore habitats with the other species in both Arctic and sub-Arctic areas [@Laurel.etal.2016; @Copeman.etal.2022]. Pacific tomcod (*Microgadus proximus*) are primarily found nearshore [@Dunn.Matarese.1987], and although not as well-studied can contribute a sizable proportion to the total gadid abundance of a community [e.g., @Willette.etal.1997; @Guo.etal.2022]. In general, gadids are highly abundant in the nearshore during early life stages (ages 0-2) which makes them important forage species [@Springer.Speckman.1997; @Laurel.etal.2016; @Gray.etal.2019]. Positive correlations among Pacific cod, pollock, and saffron cod annual nearshore abundance indicate similar pre-settlement influences on these species [@Laurel.etal.2016]. Peak timing of spawning differs by species and varies with latitude and location [reviews in @Dunn.Matarese.1987; @Doyle.Mier.2016; @Laurel.etal.2023]. Pacific cod and walleye pollock hatch offshore at depth (\~200 m), whereas Arctic and saffron cod spawn in shallower, coastal areas [@Dunn.Matarese.1987]. For Pacific cod and pollock, temperature and light mediate post-hatch vertical migrations towards surface waters [@Olla.Davis.1990; @Kendall.etal.1994], after which larva are transported via currents into nearshore habitats [@Kendall.etal.1996; @Hurst.etal.2009]. Larval distribution models in the GOA show dispersal following the westward movement of the Alaska Coastal Current demonstrating connectivity between spawning and nursery grounds [@Parada.etal.2016; @Hinckley.etal.2019]. Nursery habitat benefits, such as recruitment, growth, and condition, have been linked to broad-scale climate indices correlated with temperature that determine gyre circulation patterns and larval transport in the Pacific [@Hinckley.etal.1991; @Laurel.etal.2008; @Hurst.etal.2010; @Heintz.etal.2013; @Doyle.Mier.2016; @Hinckley.etal.2019].

Once settled in the nearshore, Pacific cod and pollock exhibit a habitat preference for seagrass and macroalgae structures [@Markis.2007; @Laurel.etal.2007; @Hurst.etal.2015]; although, some studies point to environmental conditions, such as temperature, salinity, and particularly depth, as more important influences on distribution [@Abookire.etal.2000; @Abookire.etal.2006]. Age-0 Pacific cod and age-1 saffron cod are abundant at shallow depths (\<5 m) [@Laurel.etal.2009]. Age-1 Pacific cod are more common at deeper depths (5-30 m) [@Cooper.etal.2015], but will migrate into shallow waters at night co-existing with age-0 fish [@Laurel.etkla.2009]. Diet composition overlaps between smaller Pacific cod and pollock (\<40 mm) but diverges as they grow larger [@Lee.1985], which is when Pacific cod consistently consume larger-sized zooplankton [@Strasburger.2012]. Lipid profiles of juvenile Arctic cod differ from the other species suggesting a difference in feeding particularly adapted to colder climates [@Copeman.etal.2022a]. Under recent warming trends in polar regions, Arctic cod likely experience decreased body condition [@Copeman.etal.2022b], but saffron cod may be resilient due to differential expressions of ontogeny across Arctic areas [@Copeman.etal.2015]. However, borealization of sub-Arctic species (Pacific cod and pollock) additionally increases competition among all four species as they ahve appeared to overlap more consistently [@Copeman.etal.2022a; @Wildes.etal.2022]. In the sub-Arctic, climatic warming has been linked to to larger size-at-age for Pacific cod in the GOA [@Laurel.etal.2016] and for walleye pollock in the southeastern Bering Sea [@Oke.etal.2022]. Pacific cod studies surrounding the marine heatwave years (2014-16, 2019) in the GOA found that earlier pre-settlement development best explained the larger sizes observed in warm years [@Almeida.etal.2024; @Miller.etal.2024; @Thalmann.etal.2024]. Although Pacific cod were bigger during the MHW, abundance at the end of the summer was much less than other years suggesting that mortality caused by size-selective processes could not be buffered by nursery functions [@Thalmann.etal.2024].

#### Flatfishes

Flatfishes found in the Alaskan nearshore mostly belong to the *Plueronectidae* family, whose subclasses in the North Pacific tend to associate with cold-water environments and whose early development involves migration to shallow depths [@Minami.Tanaka.1992]. During the North Pacific region shift (ca. 1976-1999), commercial abundances grew for a number of flatfish species [@Anderson.Piatt.1999], which led to increased interest in understanding their early life histories [@Norcross.etal.1995; @Norcross.etal.1997; @Abookire.Norcross.1998]. Many *Plueronectidae* taxa use nearshore areas as juveniles [@Minami.Tanaka.1992]. Early studies in Alaska primarily focused on the commercially dominant Pacific halibut (*Hippoglossus stenolepis*) and rock sole (*Lepidopsetta* spp.), and a few other commercial species that overlap in habitat, like English sole (*Parophrys vetulus*), starry flounder (*Platichthys stellatus*), and yellowfin sole (*Limanda asper*) [@Bechtol.Yuen.1995; @Holladay.Norcross.1995; @Norcross.etal.1995; @Moles.1996]. Attention was also given to arrowtooth flounder (*Atheresthes stomias*) and flathead sole (*Hippoglossoides elassodon*) [e.g., @Abookire.Norcross.1998; @Bouwens.etal.1999; @Paul.etal.2000], but their abundances tend to concentrate in the deeper parts of the nearshore (\>50 m) [@Norcross.etal.1995; @Abookire.etal.2001] which is not the 'shallow' context of interest here. Similar to the gadids, flatfish generally spawn offshore from winter-to-spring and then larval development coincides with current-driven transport to nearshore rearing habitats [reviews in @Castillo.1995; @Doyle.etal.2002; @Bailey.etal.2008]. Pre-settlement ontegeny is species specific depending on latitude [@Castillo.1995] and patterns in broad-scale oceanographic temperature and transport mechanisms [@Bailey.etal.2008; @Doyle.etal.2009; @Doyle.Mier.2012; @Cooper.etal.2014]. In the GOA and Bering Sea, Pacific halibut spawn in deep (\~400 m), cold waters during winter [@Bailey.etal.2008; @Loher.Seitz.2008], whereas rock sole, starry flounder, and yellowfin sole spawn later (spring-to-summer) followed by larval development in relatively shallower (\<200 m) and warmer waters of the coastal shelf [@Nichol.1995; @Doyle.Mier.2012; @Cooper.etal.2014]. In particular, starry flounder may migrate into much shallower, transitional waters near river mouths and sloughs to spawn [@Orcutt.1950, as cited in @Mattes.2004]. Pre-settlement ontogeny is not well documented for English sole in Alaska [c.f., @Castillo.1995], but findings from the US West Coast suggest that larval development also occurs in shallow, offshore areas and that spawning occurs early on par with halibut [@Castillo.1995] but can protract through the spring [@Doyle.etal.2002].

Research on Alaskan flatfishes in nearshore habitat began in Kodiak in the early 1990s [@Holladay.Norcross.1995; @Norcross.etal.1995]. These seminal studies focused on similar sized (\~20-100 mm) age-0 halibut, age-0 rock sole, and age-1 yellowfin sole and found species distributed differently within systems (embayments on order of \~10s of km) based on depth, temperature, and substrate parameters [@Norcross.etal.1995; @Norcross.etal.1997]. Rock sole and halibut associated with sand (vs mud or gravel) and generally shallow depths[@Norcross.etal.1997]. Halibut concentrated around the mouth of bays and were seldom found in \>50 m depth, whereas rock sole were more widely distributed in both location and depth [@Norcross.etal.1997]. Yellowfin sole were never found in \>50 m depth and associated with mixed-mud substrates near head of bay locations [@Norcross.etal.1997]. These sediment preferences were supported by lab experiments on all three species [@Moles.Norcross.1995], and field results led to habitat models that were then tested on new data from systems along the Alaska Peninsula [@Norcross.etal.1999]. Models constructed from Kodiak and Alaska Peninsula data generally all agreed but authors acknowledged the inter-relationship among physical parameters, particularly temperature and depth [@Norcross.etal.1995; @Norcross.etal.1997; @Norcross.etal.1999]. This line of research continued in the latter half of the 1990s in another system of the GOA (Kachemak Bay in lower Cook Inlet) and focused on rock sole and halibut [@Abookire.Norcross.1998; @Stoner.Abookire.2002]. Temperature and salinity gradients were not a significant influence on flatfish from Kachemak Bay [@Abookire.etal.2001], but shallow depths and sandy substrates were again important factors relating to abundance [@Abookire.Norcross.1998; @Abookire.etal.2001]. In a more recent study from the eastern Bering Sea, age-2-to-4 Alaska plaice (*Pleuronectes quadrituberculatus*) were found in the shallowest and warmest habitats with muddy substrates, similar to modeled yellowfin sole habitat [@Hurst.2016]. Interestingly age-1 halibut also concentrated in shallow habitat, but age-0 halibut were found in deeper offshore areas [@Hurst.2016]. This study did not include very shallow (\<5 m) mudflat samples, but mentions that juvenile starry flounder and age-1 and -2 yellowfin sole would have likely been more abundant if sampled [@Hurst.2016].

Like most other fishes in the Alaskan nearshore, flatfish exhibit seasonal migrations where concentrations shift from shallow depths in the summer to deep during winter [@Abookire.Norcross.1998]. Summertime residence in shallow waters aligns with the expected benefits of the nursery role hypothesis [@Beck.etal.2001]. Shallow water offers refuge from predators, and also enhances growth due to generally warmer temperatures and higher concentrations of prey ['shallow-water refuge hypothesis', @Baker.Sheaves.2007]. Being bigger during this critical period [\*sensu @*Houde.2008] can reduce mortality involving size-selective processes [@Sogard.1997]. During July and August in the GOA, water temperatures are increased and age-0 rock sole experience a peak in growth rate [@Hurst.Abookire.2006]. Increasing size also involves shifting towards deeper waters according to Heincke's Law [@Heincke.1913], which was apparent in Kodiak tethering experiments where juvenile abundances of rock sole, halibut, and yellowfin decreased with increasing depth [@Ryer.etal.2010]. Laboratory studies on halibut and starry flounder found sediment preference changed with size, suggesting it related to the ability to bury themselves [@Moles.Norcross.1995; @Stoner.Ottmar.2003]. Newly settled halibut (\<30 mm) associated with finer grain sand than larger individuals (41-80 mm) [@Stoner.Abookire.2002]. Halibut appear to lessen their sediment preference at \~80 mm [@Stoner.Abookire.2002; @Stoner.Ottmar.2003], which may translate to increased habitat availability for fishes reaching this size in the wild. In the 2000s, laboratory tests continued to explore the behavioral strategies of age-0 flatfish involving habitat selection, predator vulnerability, and foraging activity [@Stoner.Titgen.2003; @Ryer.etal.2004; @Hurst.etal.2007]. Age-0 halibut exhibited size-dependent selectivity of habitat structures (particularly sponges) where smaller individuals (50 - 150 mm) were more selective than larger ones (270-340 mm) [@Stoner.Titgen.2003]. Habitat selectivity also appears to be species-specific [@Stoner.Titgen.2003], and may result from trade-offs between predator avoidance and foraging behavior [@Ryer.etal.2004; @Hurst.2007; @Ferm.etal.2021]. When predators were introduced in a laboratory setting, age-0 rock sole showed no preference for structures [@Ryer.etal.2004], but in the field at nursery-area scales (10s of m to 10s of km) variability in density was partially explained by structures caused by emergent vegetation and worm tubes [@Stoner.etal.2007]. Back in the laboratory, age-0 rock sole exhibited risk-averse behaviors (i.e., burial, inactivity, flattened posture) whether predators were present or not [@Lemke.Ryer.2006]. By comparison, age-0 English sole exhibited more risk-prone behavior (i.e., less burying, active swimming, arched-body posture) than rock sole and halibut whether or not predators were around [@Lemke.Ryer.2006]. Age-0 halibut exhibited a stronger selection for habitat structure than rock sole [@Ryer.etal.2004], and their behavior switched between risk-averse when predators were present and risk-prone when absent [@Lemke.Ryer.2006a]. Predators encountered and consumed English sole more often than the other species, but predation rates decreased under turbid conditions (18 NTU) that are representative of the transitional waters they inhabit [@Lemke.Ryer.2006a]. The difference in behavioral strategy played out in field observations, where age-1 English sole seemed restricted to shallow refuge areas compared to age-0 and -1 rock sole that were more widely distributed [@Hurst.2007; @Hurst.2016; @Ferm.etal.2021]. Due to the relatively narrow habitat use patterns of juvenile English sole [@Ferm.etal.2021], populations may be less resilient to warming trends impacting the Bering Sea [@Yeung.Cooper.2020]. On the other hand, rock sole are widely distributed among nearshore habitats [@Ferm.etal.2021] and recruitment actually increases during warm years [@Cooper.etal.2014], suggesting populations will be more successful and could expand their northern range under continued warming trends [@Yeaung.Cooper.2020].

Other groundfishes:

-   Juvenile sablefish spend majority of their time in deeper waters, but will migrate into shallower habitats during slack high usually at dawn potentially linked to foraging [@Coutre.2014]
-   Rockfish
-   Sculpin

### Forage fishes

@Springer.Speckman.1997 defined forage fishes as "abundant, schooling fishes preyed upon by many species of seabirds, marine mammals, and other fish species." Pacific salmon and gadids are included in this definition when they are juveniles [@Spinger.Speckman.1997]. Sometimes these juveniles are the main forage fish of an ecosystem, like Arctic cod in the Beaufort and Chukchi Seas [@Graham.etal.2014; @Copeman.etal.2022]. Other species occupy this mid-trophic forage role as both adults and juveniles and could be considered 'classic' forage fishes. In Alaskan waters, classic species include Pacific herring (*Clupea pallasii*), Pacific sand lance (*Ammodytes* spp.), and various smelts (*Osmeridae)* including capelin (*Mallotus villosus*) and eulachon (*Thaleichthys pacificus*). [@Speckman.Springer.1997]. Classic forage fishes are often studied together because of overlapping spatial distributions and similar life history traits [@Blackburn.etal.1981; @Houghton.1987; @Anthony.etal.2000; @Brown.etal.2002; @Guo.2010; @Thompson.etal.2019; @Turner.2024]. In the 1970s, forage fishes occupied a large proportion of the biomass in the GOA and southeastern Bering Sea [@Francis.etal.1998; @Hunt.etal.2002]. The North Pacific regime shift towards groundfish dominance was coupled with population declines in a number forage species but most prominently in capelin and herring [@Anderson.etal.1997; @Francis.etal.1998; @Litzow.2006].

Most nearshore fishes are small-sized juveniles, which means that they could be consumed by any number of larger predators, however, classic forage species are important to understand in ecosystem food webs because their large abundances highlight major trophic pathways of energy and nutrient transfer.

Diet composition of herring, capelin, and sand lance resemble pollock more so than juvenile salmon and other gadid species [@Willette.etal.1997].

#### Smelts (Capelin and Eulachon)

#### Pacific herring

#### Pacific sand lance
