---
title: "Proposal"
author: "Chris Guo"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
output: 
  word_document: 
    toc: true
bibliography: references.bib
csl: "`r file.path(here::here(), 'doc.ignore', 'irsc.csl')`"
link-citations: true
---

```{r include=FALSE}
library(knitr)
```

# Background on nearshore fish

## Topic introduction

The marine nearshore is the relatively narrow band of waters along any oceanic coast. It is an environment that provides important ecosystem services for numerous fish species [review in @Beck.etal.2001]. Most notably the nearshore strongly impacts juvenile life stages through habitat benefits as described in the nursery role hypothesis, which states that nurseries in comparison to other habitats "must support greater contributions to adult recruitment from any combination of four factors: (1) density, (2) growth, (3) survival of juveniles, and (4) movement to adult habitats." [@Beck.etal.2001]. This hypothesis and related concepts were made popular in the 1990-2000s, and its study continues in the current literature [@Deegan.1993; @Gibson.1994; @Houde.1997; @Gillanders.etal.2003; @Dahlgren.etal.2006; @Litvin.etal.2018; @Whitfield.etal.2023]. Recently researchers have incorporated findings from other fields of ecology and statistics, adopting new approaches to data collection and analysis afforded by modern methods to further understanding of nearshore functions [@Sabetian.etal.2021; @Baker.etal.2021; @Lourenco.etal.2023; @Swadling.etal.2024].

Much of the contents of the nursery role hypothesis have become paradigm, supported by numerous studies documenting the occurrence, abundance, and growth of juveniles in nearshore habitats [@Sogard.1997; @Morin.etal.1992; @Lazzari.etal.2003; @Selleslagh.Amara.2008; @Nicolas.etal.2010; @Whitfield.Pattrick.2015; @Moore.etal.2016; @Souza.Vianna.2020]. In the last two decades, there has been strong support in the literature for expansion of nearshore benefits to include ideas like habitat connectivity and ‘seascape’ effects [@Ray.2005; @Nagelkerken.etal.2015; @Litvin.etal.2018; @Seitz.etal.2020]. These migration-related topics have mostly been studied for singular taxa then synthesized in meta-analysis [@Gillanders.etal.2003; @Minello.etal.2003; @Hodgson.etal.2020; @Whitfield.etal.2023]. Relatively few nearshore studies have been able to address this at the community level [c.f., @Sheaves.2009; @Valesini.etal.2014; @Ricart.etal.2018], although doing so would improve understanding of how connectivity functions with other ecological mechanisms that affect fishes, such as species interactions, trophic dynamics, or changes to habitat quality and quantity [@Gibson.1994; @Tjelmeland.1997; @Able.1999; @Able.2005; @Sheaves.2009; @Sheaves.etal.2015].

Issues of scale add an additional level of complexity to our understanding of communities in relation their environment [@Wiens.1989; @Levin.1992; @Chave.2013]. In the field of community ecology, sample autocorrelation and scale-mediated effects are known hurdles to overcome if studies wish to generalize beyond a particular system [@Legendre.Fortin.1989; @Fukami.2004; @Irvine.etal.2011; @Dray.etal.2012; @Guenard.Legendre.2018]. Climate issues have been given increased attention recently, where studies have linked anomalous environmental observations with potential ecosystem responses and raised concerns for future resource management [@Rindorf.Lewy.2006; @Lindmark.etal.2019; @Reinl.etal.2025]. In areas where long-term environmental data exist, species and community metrics can be related to multi-year or decadal patterns [@Attrill.Power.2002; @Siwertsson.etal.2024; @Araujo.etal.2025], or biological outcomes can be inferred from periodically defined events (e.g., human activities, historic floods, MHWs) [@Cloern.etal.2016; @Bachand.Walsh.2022; @Ziegler.etal.2023]. Oceanographic measurements at a basin-wide scale exhibit similar trends in the long-term but coastal observations can vary in magnitude or even contrast with the regional pattern [@Danielson.etal.2022], making nearshore fishes dependent on local and regional contexts. At the meta-community level multiple scales need to be considered in order to reveal which processes may be structural [@Logue.etal.2011; @DAmen.etal.2017; @Thompson.etal.2020], especially since fish–environment relationships can vary at different scales and models will differ in how they fit and disentangle autocorrelated effects [@Guzman.etal.2022; @Leibold.etal.2022; @Viana.etal.2022].

## Community organization

Nearshore fish communities been researched globally for decades, where a particular density of studies come from temperate regions of Europe, Australia, and South Africa [@Potter.etal.1990; @Harrison.Whitfield.2006; @Elliott.etal.2007; @Sheaves.2009; @Sheaves.etal.2015; @Whitfield.2020; @Nodo.etal.2023]. Other impactful studies, while less prominent in the literature, have come from parts of the Americas and more polar regions of Europe [@Deegan.1993; @Stenseth.etal.2002; @Rueda.Defeo.2003; @Sielfeld.etal.2010; @Barcelo.etal.2016], although my literature search is probably biased towards those in english. Most bodies of research have started at the local scale comparing community structure (as alpha and beta diversity) to physicochemical conditions among sites that are \~10s of km apart [@Blaber.Blaber.1980; @Morin.etal.1992; @Potter.etal.1997; @Bennett.1989]. The studied conditions are typically hypothesized a priori and have resulted in significant effects from temperature, salinity, turbidity, or water velocity [@Cyrus.Blaber.1987; @Bottom.Jones.1990; @Abookire.etal.2000; @Rueda.Defeo.2003; @Maes.etal.2004; @Sosa-Lopez.etal.2007; @MarinJarrin.Shanks.2011; @Kisten.etal.2020]. Numerous additional metrics of water quality and physical conditions have also been found to be important, although which parameters that result in highest impact can differ based on the study area [@Stoner.Abookire.2002; @Jaafar.etal.2004; @Maes.etal.2004; @Mateo.Tobias.2004; @Nunoo.etal.2006; @Selleslagh.Amara.2008; @Franca.etal.2012], and so early studies tend to acknowledge uncertainty when translating their findings to other systems. Comparison of habitat types is another common study design at the sub-region scale [@Dean.etal.2000; @Lazzari.etal.2003; @Johnson.etal.2010; @Schein.etal.2012]. Review of such work found that complex, structured habitats (e.g., seagrass, mangroves, kelp forests) are usually more effective in terms of nursery role benefits than unstructured habitats (e.g., bare substrate, open water) [@Minello.etal.2003; @Lefcheck.etal.2019]. Although, connectivity among multiple habitat types - including those with less complexity - is also an important aspect of nursery function [@Nagelkerken.etal.2015; @Litvin.etal.2018; @Swadling.etal.2019; @Swadling.etal.2024], allowing species to migrate and distribute differently in relation to predation, growth, or density [@Ryer.1988; @Laurel.etal.2007; @Nash.etal.2007; @Stoner.etal.2007; @Ciannelli.Bailey.2005; @Meynecke.etal.2008; @Munsch.etal.2016].

### Spatial structures

At larger spatial scales, variability in community structure is dominated by factors that differ among ecosystems, such as latitude and coastal formation, rather than those that more so characterize the site level like hydrology or habitat. The overall pool of species varies with latitude, or more generally distance, on the scale of regions (1000s of km) [@Ojeda.etal.2000; @Sielfeld.etal.2010; @Navarrete.etal.2014]. Additionally, communities are either described in the context of marine or estuarine settings (sometimes referred to as ‘transitional waters’) because of the conditions that physiologically favor euryhaline-adapted fishes [@Beck.etal.2001; @Whitfield.Pattrick.2015; @Bradley.etal.2019]. Studies also find differences in community structure when comparing systems with contrasting geomorphologies [@Franca.etal.2012; @ShahEsmaeili.etal.2022; @Laske.etal.2024]. These comparisons are somewhat intuitive among systems (10s to 100s of km), where researchers can easily delineate samples based on coastal form (e.g., open beaches, bights, fjords, lagoons) and type (e.g., closed, open, semi-open) of an area, and its associated features (e.g., watershed type, freshwater source, anthropogenic influence) using geographic measurements such as total area, shoreline complexity, or distances among features [@Rueda.Defeo.2003; @Harrison.Whitfield.2006; @Meynecke.etal.2008; @Nicolas.etal.2010; @Miller.etal.2014]. Generally, nearshore communities vary at multiple spatial scales: structural differences among sites (beta diversity) can be attributed to a multitude of factors or gradients that depend on the context of the system, whereas structural changes (gamma diversity) and patterns across systems and regions (zeta diversity) are similarly scaled to mechanisms operating on the broader species pool [@Pittman.etal.2004; @Sielfeld.etal.2010; @Hattab.etal.2015; @Pasquaud.etal.2015].

### Temporal structures

Despite wide spatial variability, dominance by juvenile life stages in the community is ubiquitous among nearshore studies. Studies report of community patterns over shorter time scales (e.g., night vs day, tidal fluctuations, seasonal periods) [@Maes.etal.2004; @MarinJarrin.Shanks.2011; @Torre.etal.2017], which is caused by to the variability in ontogenetic patterns exhibited by community members [@Elliott.etal.2007; @Potter.etal.2015]. Therefore, seasonal patterns of occurrence and abundance are often attributed to the different life histories that functionally lead fishes into the nearshore [@ShahEsmaeili.etal.2022], such as the various forms of diadromy [@Ray.2005]. Nearshore residence, recruitment timing, and size have also been related to seasonal prey availability, hydrological gradients, and habitat features, among other (often system-specific) factors [@Moore.etal.2016; @Kindong.etal.2020; @Barton.etal.2020; @Luo.etal.2023]. While seasonal influences have been widely reported, interannual effects are somewhat less common and appear more difficult to explain. Community studies that do analyse interannual effects have typically reported on shorter periods (\~2-4 yrs) [e.g., @Thedinga.etal.2013; @Roux.etal.2016; @Sutton.etal.2025], which is usually insufficient to measure the effect of nearshore function on community members [@Able.1999].

More recent literature has been able to discuss long-term change because some places have accrued large time series of community observations (several years to decades). Researchers can couple these data with long-term environmental monitoring datasets [@Cloern.etal.2016] or oceanographic indices (e.g., ENSO, NAO, PDO) [@Collie.etal.2008; @Sielfeld.etal.2010; @Araujo.etal.2025]. Structural changes in species residency, abundance, density, and growth have been linked to shifts in the environment described by anomalous conditions, physicochemical gradients, and habitat changes [@Baptista.etal.2015; @Barcelo.etal.2016; @Amorim.etal.2017; @Beukhof.etal.2019; @Langan.etal.2021; @Priest.etal.2022; @Castillo.etal.2023]. A number of studies have also compared fish responses among distinct temporal periods defined by shifts in the environment or sometimes by gaps in sample years [e.g., @Heintz.etal.2013; @vonBiela.etal.2023; @Ziegler.etal.2023; @Almeida.etal.2024; @Geoghegan.etal.2025]. There is evidence that nursery benefits may be reduced due to periodic disturbances [@Sabetian.etal.2021; @Thalmann.etal.2024], although conservation areas (e.g., MPAs) appear to provide resiliency during and after such periods [@Ziegler.etal.2023]. Community variability over long time scales can be a useful metric for discovering structural shifts attributed environmental change (e.g., climate, habitat, regime) as opposed to cyclical population dynamics. Still, identifying the exact mechanisms driving community shifts likely lies in understanding ontogeny at the species or metapopulation level [e.g., @Laurel.etal.2016; @Thalmann.etal.2024].

## Alaskan nearshore fish communities

In Alaska, community-level research on nearshore fishes gained momentum in the 1970s when environmental assessments were sought in anticipation of oil and gas lease sales and to inform emergent fisheries [e.g., @Harris.Hartt.1977]. Since then, the most consistently studied areas continue to be the Beaufort Sea and the Gulf of Alaska - specifically southeast Alaska (SEAK), Kodiak, lower Cook Inlet, and Prince William Sound [@Craig.1984; @Rogers.etal.1986]. Although more concentrated in the earlier decades of nearshore research, community data has also been collected from the Aleutian Islands, Bering Sea, and Chukchi Sea [e.g., @Fechhelm.etal.1984; @Isakson.etal.1986; @Craig.1987]. Over the years, there have been many more studies focused on particular fish species or functional groups compared to those on whole communities. These have produced useful findings on how certain fishes behave and distribute in the nearshore [e.g., @Jaenicke.etal.1985; @Dunn.Matarese.1987; @Johnson.etal.2003; @Hurst.2016; @Gray.etal.2019]. However, understanding the ecological processes acting on whole communities requires a multi-species approach, which is my focus here. Inconveniently, studies have often differed in how nearshore waters were defined [e.g., @Kendall.etal.1980; @Thorsteinson.etal.1991; @Mueter.Norcross.1999], making interpretation difficult among the reported communities. Sampling fishes in the shallow waters closest to shore typically involves a beach seine, fyke net, or trammel net [see gear descriptions in @Rogers.etal.1984 and @Domke.etal.2024]. Sometimes studies have targeted specific depth ranges further offshore [e.g., trawl gear as in @Mueter.Norcross.1999], while others have used methods without explicit depth control [e.g., eDNA collection as in @Larson.etal.2022]. Herein, I refer to the "nearshore" as the shallowest areas directly adjacent to the coast (usually \<5 m depth and \<50 m from shore). In the following sections, referenced information draws specifically from collections made in the nearshore using typical methods, although broader studies are sometimes referred to for supportive information.

### Beaufort and Chukchi Seas

The Arctic nearshore is physically distinct from other regions of Alaska because of the presence of sea ice for 6-7 months of the year and the formation of coastal lagoons which are recognized as important fish habitats [@vonBiela.etal.2023; @Laske.etal.2024]. The Arctic coast also includes embayments of varying sizes, large river deltas, and exposed shorelines [@Craig.1984; @Fechhelm.etal.1984]. Ice scouring makes the nearshore relatively devoid of physical structuring, so fishes may rely on differences in water conditions for refugia [@Logerwell.etal.2015]. Seasonal timing of ice break up and river discharge drives coastal hydrology Arctic-wide [@Fechhelm.etal.1984; @Jarvela.Thorsteinson.1999; @Dunton.etal.2006], while local conditions are heavily influenced by the direction and magnitude of prevailing winds [@Craig.1984; @Fechhelm.etal.1984]. Wind vectors determine the extent of fresh-marine mixing, at times keeping relatively low-saline warm waters pressed against the coast, and at other times extending a fresh surface lens seaward causing cold marine waters to wedge in towards shore [@Craig.1984]. These dynamics can shift on the order of days leading to potentially rapid changes in fish assemblage [@Craig.1984; @Thorsteinson.etal.1991]. Lagoons, however, receive some protection from barrier islands creating habitats that can maintain conditions better than exposed beaches [@Jarvela.Thorsteinson.1999; @Logerwell.etal.2015], although the balance of fresh-marine water masses within lagoons are still largely driven by wind [@Laske.etal.2024].

The Beaufort and northeast Chukchi share many common species in the nearshore [@George.etal.2009; @Johnson.etal.2012], but distributions can differ among regions in terms of seasonal occurrence, habitat usage, and/or life history stage [reviewed in @Thorsteinson.Love.2016]. Species well-adapted to euryhaline conditions (estuarine) become abundant during the ice-free season when brackish waters take over the nearshore [@Craig.1984]. The most common estuarine fishes come from the family Salmonidae including the whitefishes, ciscoes, salmon, and char. Whitefishes and ciscoes (*Coregonus* spp.) are more represented in the Arctic than other regions of Alaska [@Johnson.etal.2012], with broad whitefish (*C. nasus*), humpback whitefish (*C. pidschian*), Arctic cisco (*C. autumnalis*), and least cisco (*C. sardinella*) as most common. By comparison, Pacific salmon (*Oncorhynchus* spp.) are not well represented in the Arctic, except that pink salmon (*O. gorbuscha*) and chum salmon (*O. keta*) occur frequently in the Chukchi and western Beaufort. Dolly Varden (*Salvelinus malma*, called "Arctic char" prior to 1990s) and rainbow smelt (*Osmerus dentex* prev. *mordax*, also called "Arctic smelt" and "boreal smelt") are common throughout the Arctic sub-regions [@Thorsteinson.Love.2016]. All of these estuarine fishes exhibit either amphidromy or anadromy [@Khalsa.etal.2021], and so are more commonly found in delta habitats near natal waters. Nearshore fishes with more stenohaline preferences (marine) are largely comprised of classic forage fishes and groundfishes, many of which exhibit nearshore spawning behavior. The most dominant forage fishes are Pacific capelin (*Mallotus catervarius*, mostly called *villosus*), Arctic sand lance (*Ammodytes hexapterus*), and to a lesser extent Pacific herring (*Clupeidae pallasii*) [@Thorsteinson.Love.2016]. These forage fishes, including rainbow smelt, prefer lagoon and beaches as nursery habitats due to warm conditions and proximity to spawning grounds [@Logerwell.etal.2015]. Arctic cod (*Boreogadus saida*, called "polar cod" outside of Alaskan literature) and saffron cod (*Eleginus gracilis*) receive a large amount of research attention due to their role in the ecosystem as it relates to decreasing sea ice [@vonBiela.etal.2023]. The fourhorn sculpin (*Myoxocephalus quadricornis*), one of the most ubiquitous nearshore species, persists in the nearshore year-round as juvenile and adult stages. Whereas, the highly common shorthorn sculpin (*M. scorpius*) only remain in the nearshore as juveniles [@Thorsteinson.Love.2016]. Other marine species, like the whitespotted greenling (*Hexagrammos stelleri*), similarly use nearshore habitats year-round in their juvenile stage but adults also migrate into the nearshore during summer [@Thorsteinson.Love.2016].

Nearshore studies distinguish between the Beaufort and the Chukchi by contrasting environmental contexts and the associated communities [@Craig.1984; @Johnson.etal.2012; @Vollenweider.etal.2017]. Relatively more information has been available for the Beaufort beginning with numerous early surveys ca. 1970-80s [review in @Craig.1984] and including more recent studies [@Priest.etal.2022; @Laske.etal.2024]. The Alaskan Beaufort has been divided into broad sub-regions defined by slow-flowing, tundra-fed rivers in the west and fast-flowing, mountainous rivers in the east [@Schmidt.etal.1983; @Craig.1984]. These watersheds cumulatively maintain a narrow band of estuarine habitat - turbid, warm, and brackish conditions - that is more or less continuous along the Beaufort coast (\~750 km) during the ice-free season [@Craig.1984; @Dunton.etal.2006]. Salmonidae fishes (e.g., ciscoes, salmons, whitefishes) depend on the brackish band as migration corridors for spawning adults, and productive feeding grounds for juveniles [@Schmidt.etal.1983; @Thorsteinson.etal.1991]. Anadromous juveniles disperse into the nearshore differently between sub-regions, where watersheds in the west better support salmon and whitefish species while mountainous systems in the east favor Arctic char and Arctic cisco [@Craig.1984]. Runoff decreases as the season progresses leading to increased salinity and higher relative abundances of marine species such as Arctic cod, fourhorn sculpin, and Arctic flounder [@Fechhelm.etal.1984; @Vollenweider.etal.2017; @Priest.etal.2022]. In a study comparing lagoon communities spread across central and eastern Beaufort sub-regions, @Laske.etal.2024 found community composition associated with differing salinity conditions among sites \>50 km apart. @Priest.etal.2022 also found significantly different community structures associated with salinity among sites separated over short distances (\~5-10 km). Annual variability in sea ice and meteorological conditions influence the timing and formation of the brackish band, and temperature appears to explain interannual differences in assemblages [@Jarvela.Thorsteinson.1999; @Priest.etal.2022]. In Prudhoe Bay from 2001-2018, the annual abundances of broad whitefish and saffron cod exhibited positive linear trends correlated with temperature [@Priest.etal.2022]. At lagoon sites near Kaktovik, saffron cod similarly increased in abundance over periods representing declining sea ice (ca. 1990, 2004, 2018), while fourhorn sculpin abundance decreased and Dolly Varden apparently shifted towards deeper habitats [@vonBiela.etal.2023].

Early Chukchi research was limited to a single study in the northeast sub-region [@Fechhelm.etal.1984]. The Chukchi nearshore does not maintain a brackish band and is seen as more marine-influenced compared to the Beaufort due to large sections of exposed coastline [@Fechhelm.etal.1984; @Logerwell.etal.2015]. Chukchi lagoon habitats tend to receive more marine exchange between barrier island formations [@Fechhelm.etal.1984], which influences the trophic ecology within lagoons [@Fraley.etal.2021a] and structures the community differently than other habitats [@Barton.etal.2020]. Lagoon habitats can be highly productive, where salinity covaries with the abundance of copepods, which correlates to increased fish species abundances [@Barton.etal.2020]. In July-August 1983, lagoon samples had higher abundance (\~5x) on the outside of barrier islands than inside, with mostly juveniles (\<130 mm) of marine-associated species (e.g., Arctic cod, capelin, fourhorn sculpin, Arctic flounder) dominating the catch [@Fechhelm.etal.1984]. More recent Chukchi studies (ca. 2005-2015) also focused in the northeast and particularly on the section of coast \~50 km from Pt. Barrow [@Thedinga.etal.2013; @Logerwell.etal.2015; @Barton.etal.2020]. @Thedinga.etal.2013 was the first to revisit the northeastern Chukchi nearshore in 2007-09, finding that species assemblage was similar to past studies in the area [@Fechhelm.etal.1984] and composition generally resembled those in marine habitats (as opposed to brackish) from the Beaufort Sea [@Craig.1984]. Overall catch was positively correlated with temperature, where either Arctic cod or capelin dominated relative abundance during cold or warm years, respectively [@Thedinga.etal.2013]. This same data [August-September 2007-2009, @Thedinga.etal.2013] was incorporated into a another broader study comparing fish habitats from the northeast Chukchi and western Beaufort [@Logerwell.etal.2015]. In those years, Arctic cod dominated the nearshore abundance in the Beaufort while capelin was dominant in the Chukchi [@Logerwell.etal.2015]. By studying a range of habitats including those offshore, @Logerwell.etal.2015 demonstrated that juvenile Arctic cod distributed widely and were not restricted to the nearshore, suggesting variable strategies for during early life stages. By contrast, juvenile saffron cod was more restricted to the nearshore in the Beaufort but not in the Chukchi, exhibiting a regional difference in early life history expression [@Logerwell.etal.2015]. Additionally, communities of the Chukchi Sea appear more prone to effects of reduced sea ice than the Beaufort as its connection with the Bering Sea allows more influence from low-latitude fishes [@Grebmeier.2012]. Especially during warm years, species such as saffron cod, sand lance, and capelin dominate nearshore communities [@Barton.etal.2020].

### Bering Sea and Aleutian Islands

The Bering Sea environment shares similar seasonal influences as the Arctic regions, but its lower-latitude position makes impacts from reduced sea ice relatively stronger here [@Grebmeier.2012]. Arctic specialists are not as common in the Bering Sea, where coastal communities are moreso dominated by boreal species like starry flounder (*Platichthys stellatus*), walleye pollock (*Gadus chalcogramma,* also called *Theragra*), and rainbow smelt [@Barton.1978; @Isakson.etal.1986; @Thedinga.etal.2008]. Similar to the differences among Chukchi-Beaufort regions, the Bering Sea has northern and southern regions differing in environmental conditions [@Grebmeier.2012], with the southeastern coast receiving the most attention in terms of nearshore research. Finfish fisheries in the Bering Sea have historically relied on Pacific herring and Pacific salmon populations, which led early surveys and reports to focus collections on these species [@Barton.1978; @Isakson.etal.1986]. In a singular early study on the nearshore of the northeast region, @Barton.1978 documented species caught during June-October 1976-77 from around Norton Sound, including Port Clarence (north end), the Yukon River delta (south end), and parts of the central coast. Generally, all areas shared similar proportions of marine and estuarine species (\~50% per type), but estuarine species dominated in brackish habitats found inside Port Clarence and at the Yukon delta [@Barton.1978]. Herring and salmon juveniles were highly abundant in the nearshore, and in particular chums and pinks were around during the first month after break-up [@Barton.1978]. Early catches also frequently encountered starry flounder and high abundances of larval forms identified among families Osmeridae (as either rainbow or pond smelt), Cottidae, and Gadidae [@Barton.1978].

Studies from the southeastern Bering offer a little more nearshore information, although geographically limited to the Aleutians side of Bristol Bay in the 1980s [@Isakson.etal.1986; @Craig.1987] and around Unalaska in 2005 [@Thedinga.etal.2008]. @Isakson.etal.1986 initially described shallow nearshore communities as a result of summer surveys during 1984-85, and also by reviewing of prior work in the area ca. 1960-1985. Based on prior research, the dominant nearshore fishes were expected to include Pacific sand lance [*A. personatus*, but likely incorrectly referred as *hexapterus* prior to @Orr.etal.2015], capelin, yellowfin sole (*Limanda aspera*), rock sole (*Lepidopsetta* spp.), and herring [@Isakson.etal.1986]. Note that studies sometimes report either northern (*L. polxystra*) and/or southern rock sole (*L. bilineata*, also called "Pacific"), however, I refer to both together since they are hard to distinguish in field and studies do not indicate how identifications were made. In 1984-85, the most abundant species were sand lance followed by juvenile chum salmon, although almost all chums were caught in 1985 when collections began a couple weeks earlier (mid-June) than they did in 1984 [@Isakson.etal.1986]. Other abundant species from 1984-85 were not necessarily expected, some of which included surf smelt (*Hypomesus pretiosus*), Pacific staghorn sculpin (*Leptocottus armatus*), and starry flounder [@Isakson.etal.1986]. In discussion the authors cited differential habitat types (e.g., vegetated or not) as potential sources of variability in nearshore distributions, especially concerning juvenile flatfish use of nursery areas [@Isakson.etal.1986]. @Craig.1987 also collected new data and reviewed prior studies [including @Isakson.etal.1986] from the southeastern Bering, and further characterized distributions in species abundances. Fishes were categorized into functional groups of forage fishes, salmon, and demersal fishes, and nearshore residents, while the environment was broadly separated into exposed and protected habitats [@Craig.1987]. Both habitat types shared a number of dominant species (\>10% catch) that were also mentioned by @Isakson.etal.1986, but @Craig.1987 additionally reported Pacific cod (*G. macrocephalus*), sockeye salmon (*O. nerka*), and Dolly Varden. Species richness was higher in protected habitats, which were dominated by walleye pollock, coho salmon (*O. kisutch*), whitespotted greenling, masked greenling (*H. octogrammus*), surf smelt, and tubenose poacher (*Pallasina barbata*) [@Craig.1987]. By contrast, Pacific sandfish (*Trichodon trichodon)* and capelin were representatively dominant in exposed habitats [@Craig.1987]. Temporal variability was most evident in the large pulses of forage fishes and salmon during their respective spawning and/or juvenile outmigration periods, whereas demersal species tended to be more consistently abundant. Seasonal signals were also apparent where, for example, sand lance and juvenile walleye pollock were only abundant during summer [@Craig.1987]. Seasonality in species distributions also differed according to habitat. For instance, Dolly Varden were transient in lagoons during summer but could also be abundant in exposed habitats at various times throughout the year [@Craig.1987]. Tubenose poachers, whitespotted greenling, and masked greenling were residents of protected habitat only, but staghorn sculpin and starry flounder were persistent residents regardless of habitat [@Craig.1987].

Since the 1980s community-level research was pretty limited in the Bering Sea, with only a few nearshore surveys conducted around Unalaska and Akutan [@Robards.1999; @Robards.Schroeder.2000; @Thedinga.etal.2008]. Of those studies, @Thedinga.etal.2008 had the more thorough assessment of nearshore fishes, documenting species abundances and sizes observed in various habitats. Although collections were only made from June 2005, there were a large number of sites (n = 70) representing three types of habitats: non-vegetated sand, vegetated cobble, and vegetated bedrock [@Thedinga.etal.2008]. Sand lance represented the most abundant species, contributing to more than a third of all fish caught, but was almost entirely specific to sand habitat [@Thedinga.etal.2008]. This differed from other findings in the area by @Robards.1999 and @Robards.Schroeder.2000, who found very few sand lance but instead reported communities dominated by pink salmon fry. In 2005, gadids (mostly walleye pollock), pink salmon, sandfish, and snake prickleback (*Lumpenus sagitta*) were the next most abundant and were specific to cobble habitat. These five most-abundant species - collectively 98% of the overall catch - were found in sand and cobble substrates, while bedrock habitat contributed relatively little [@Thedinga.etal.2008]. Juvenile gadids and silverspotted sculpin (*Blepsias cirrosus*) were both frequent occurrences in both cobble and bedrock sites, indicating a possible preference for vegetation. In general, fish sizes suggested that juveniles dominated the community, with pink salmon, gadids, and sandfish entirely of age-0, while sand lance and snake prickleback exhibited two or three age-groups [@Thedinga.etal.2008]. Rock sole and rock greenling (*H. lagocephalus*) had both juvenile and adult size classes represented, suggesting that these species were true nearshore residents. Authors noted that the study sites did not include spawning areas for forage fishes (sand lance, herring, capelin, sandfish), so mostly juvenile forms were captured and that the associated habitats (sand and cobble substrates) likely represented important nurseries [@Thedinga.etal.2008].

Some community information from the Aleutian Islands was available in reports dating back to the 1960s although the findings were not specific to the nearshore [e.g., @Isakson.etal.1971]. Surveys conducted in the 1970s offer good descriptions of nearshore fish communities [@Hancock.1975; @Simenstad.etal.1978], but information since then has been somewhat lacking [except see @Arimitsu.Piatt.2008]. The Aleutians can be separated into sub-regions based on certain passes between major land formations which result in different oceanographic conditions depending on the source of the dominant current (i.e., Alaska Coastal Current, Alaska Stream, or Aleutian North Slope Current) [@Hunt.Stabeno.2005; @Logerwell.etal.2005; @Gharrett.etal.2012; @Konar.etal.2015]. Nearshore studies ca. 2000s from Unalaska and Akutan [@Robards.1999; @Robards.Schroeder.2000; @Thedinga.etal.2008] were moreso representative of conditions in the southeastern Bering Sea, while studies from the rest of the Aleutians were likely describing distinct eco-regions separating the region [@Hancock.1975; @Simenstad.etal.1977; @Simenstad.Nakatani.1977; @Simenstad.etal.1978; @Hunt.Stabeno.2005; @Arimitsu.Piatt.2008; @Konar.etal.2015].

Over one calendar year in 1972-73, @Hancock.1975 documented the abundance and size distributions of the nearshore fishes in Clam Lagoon (\~5 km^2^) on Adak Island. Seasonal signals were found in the fish community and environmental conditions, where temperatures rose and wind velocity fell during summer months while salinity remained relatively stable [@Hancock.1975]. Species were mostly juvenile form and expressed different nearshore timing and residency periods. Richness and abundance correlated positively with temperature during spring and summer months, however, most species left the lagoon prior to temperatures beginning to drop in September suggesting that local conditions were not causing temporal distributions [@Hancock.1975]. Rock sole and starry flounder were present from April to November as nearshore residents [@Hancock.1975]. Great sculpin (*M. polyacanthocephalus*) appeared about a month later in May but also remained until November [@Hancock.1975]. Sand lance and juvenile pink salmon exhibited a pulse-like residence (abundant and short) representative of their respective spawning and outmigration patterns [@Hancock.1975]. Assemblages differed by sediment type, where juveniles of armorhead sculpin (*Gymnocanthus galeatus*) and tubenose poacher were specific found in sand or pebble substrates, respectively [@Hancock.1975]. In discussion, @Hancock.1975 also noted how communities appeared to differ by site location and suggested that a possible structuring process was exposure to wave action.

In 1976-77, @Simenstad.etal.1978 examined nearshore habitats on Attu Island that differed in sea otter predation, with one area experiencing recent population expansion (Massacre Bay) contrasted by another with relatively no otters (Chichagof Harbor). Coastal exposure and substrate were discussed as other habitat characteristics possibly affecting species composition, similar to findings from Adak in 1972-73 [@Hancock.1975; @Simenstad.etal.1978]. Juvenile pink salmon, sand lance, rock sole, and juvenile sculpins (possibly *Gymnocanthus* sp.) were representative of protected sand-gravel habitat, while rock greenling (*H. lagocephalus*), great sculpin, and red Irish lord (*Hemilepidotus hemilepidotus*) were dominant species in exposed rocky habitat, which was also where the kelp beds were primarily located [@Simenstad.etal.1978]. Species compositions were not significantly different between the two areas, but fish abundances were generally higher at sites with higher macroalgae abundance [@Simenstad.Nakatani.1977; @Simenstad.etal.1978]. When Attu communities were compared to those from Amchitka, where otters had been established for years [@Simenstad.etal.1977], differences in species compositions revealed direct and indirect effects on nearshore fishes from otters [@Simenstad.etal.1978]. In the relative absence of sea otter predation, increased activity from herbivorous macroinvertebrates - primarily sea urchins - resulted in decreased habitat resources originating from macroalgae [@Simenstad.etal.1978]. Sea otters influenced the invertebrate prey of nearshore fishes, namely rock greenling, whose stomach contents indicated that detritus-feeding crustaceans (amphipods, mysids) were more available when otters controlled the food web [@Simenstad.Nakatani.1977; @Simenstad.etal.1978]. Sea otters also directly affected nearshore fishes through predation, where populations of rock greenling at Amchitka appeared smaller than those at Attu apparently caused by size selectivity [@Simenstad.etal.1978].

The influence of otters and kelp on fish community was revisited by @Reisewitz.etal.2006, who compared certain islands (Amchitka and Adak) during periods before (1986-87) and after (1998-2000) the otter population crashed. Although fish collections were not meant to capture responses in fish communities from the nearshore *per se* - instead, rock greenling were targeted by trammel net in 10-15 m depth - a strong comparison could be made because the same methods were used at the same sites in both periods [@Reisewitz.etal.2006]. After the decline in sea otters, kelp densities decreased which coincided with a decrease in rock greenling abundance [@Reisewitz.etal.2006]. Interestingly, the overall diversity (Shannon-Wiener) and the abundance of other fishes had both increased, although this pattern was also observed where otters were already rare or absent (Attu and Shemya) indicating that they were not a causal factor [@Reisewitz.etal.2006]. Later in 2009-10, @Konar.etal.2015 studied the effect of habitat on fish community variability across the Aleutians (Unalaska to Attu) and found non-significant differences caused by habitat type (kelp forest vs urchin barren) or kelp forest edge effects (interior vs margins). Fish data were visually collected with SCUBA transects at 6-12 m depth (B. Konar, personal communication), which differed from past studies but did not result in much discrepancy from expected assemblages [@Simenstad.etal.1977; @Konar.etal.2015]. Pacific cod and rock greenling were relative abundant, and other common taxa included kelp greening (*H. decagrammus*), red Irish lord, rock sole, and various members of family Sebastidae [@Konar.etal.2015]. Certain species exhibited specificity at larger spatial scales. For example, Pacific cod often dominated where they occurred in the western and central Aleutians, whereas sand lance were only captured from the eastern Aleutians around Unalaska [@Konar.etal.2015]. Most of the community variation was explained by the smallest spatial scale (sites within islands), whereas much less variation was explained by the factors representing broader scales as individual islands or groups of islands [@Konar.etal.2015]. The authors suggested that kelp forests in the western and central Aleutians had little remaining influence on fish community since their densities decreased years ago following the otter collapse, and that observed differences in assemblage in the Aleutians was moreso related to oceanographic patterns [@Hunt.Stabeno.2005; @Konar.etal.2015].

A variety of gear types were used in fish collections across the Aleutians over the years, resulting in community descriptions that are either outdated [@Hancock.1975] or not quite compatible with our nearshore definition [@Simenstad.etal.1978; @Reisewitz.etal.2006; @Konar.etal.2015]. An exception to this is a study by @Arimitsu.Piatt.2008, who conducted beach seines across the eastern and central Aleutians (Aghiyuk to Adak) during summer of 2006. Species CPUE did not differ significantly among habitat, substrate, beach incline, or kelp cover, but authors suggest that weak results may have been due to the combination of low effort over a relatively large spatial area and the opportunistic nature in sampling schedule [@Arimitsu.Piatt.2008]. The research objectives of the study were centered around monitoring forage fishes, in which the major species exhibited somewhat limited nearshore distributions. The majority of samples (\>80%) were collected from the Andreanof Islands, where sand lance and juvenile gadids (Pacific cod, walleye pollock, and unidentified age-0) were most frequently encountered [@Arimitsu.Piatt.2008]. Comparatively, capelin were even more restricted in distribution (CPUE and frequency of occurrence) and found in a limited number of samples from Shumagin and Adak [@Arimitsu.Piatt.2008]. While not highly frequent (30% of samples), juvenile pink salmon were the most abundant species primarily captured near freshwater outflows [@Arimitsu.Piatt.2008]. Other taxa that occurred with moderate frequency (19-30% of samples) included unidentified age-0 sculpins (Cottidae, \<32 mm length), Dolly Varden, rock greenling, great sculpin, silverspotted sculpin, and rock sole [@Arimitsu.Piatt.2008].

### Gulf of Alaska

# Dissertation theme

Topics:

-   Community analysis

-   Hierarchical structure (?)

-   Macroecology [@Leibold.etal.2004],

-   Juvenile fishes, Nearshore function

-   Spatial autocorrelation

-   Climate indices, Marine heatwaves

Ecological principles:

-   nursery role hypothesis [@Beck.etal.2001; @Gillanders.etal.2003; @Dahlgren.etal.2006]

    -   updates to [@Sheaves.2009; @Sheaves.etal.2015; @Litvin.etal.2018; @Swadling.etal.2024]

    -   shallow water refuge paradigm [@Baker.Sheaves.2007]

        -   good review in [@Ryer.1988]

        -   size depth rule, Heincke's Law [@Heincke.1913]

        -   reduced predation paradigm [@Blaber.Blaber.1980; @Whitfield.2020]

        -   predator behavior with structural complexity [@Bartholomew.etal.2000]

-   critical period hypothesis [@Hjort.1914; @Houde.2008]

    -   variations [see Paul.etal.1995 in Proc of the Intl Symp of N Pac Flatfish]

        -   match-mismatch hypothesis (Cushing 1975)

        -   stable ocean hypothesis (Lasker 1975)

    -   framework [@Doyle.Mier.2012]

    -   temperature size rule [@Atkinson.1994; @Atkinson.etal.2006]

        -   temperature bottlenecks [@Dahlke.etal.2020]

        -   temperature growth [@Searcy.etal.2007]

    -   density dependent processes

        -   critical size rule [@Sogard.1997]

        -   critical weight rule [@Cowan.etal.2000]

        -   concentration hypothesis [@Beverton.1995]

        -   self-thinning rule [@Nash.etal.2007]

Community analysis was developed recognizing ecological principles based on species interactions and was meant to address questions of biodiversity, distribution, management, and change over time. Macro-community analysis... theoretical and (very recently) empirical

-   Community ecology based on species distributions, abundances, and possible interactions

-   Metacommunity framework dictates 4 paradigms:

    -   Neutral theory (null) -

        -   defined by slow, random patterns of compositional change in space and through time

        -   unlike other approaches, there is no presumption of species difference in niche relationships with local factors and/or in abilities to disperse or avoid local extinctions

        -   differences in local and regional diversity are random, or else could be explained by the other paradigms

    -   Patch-dynamics (dispersal among identical localities) -

        -   built on dispersal/extinction theory, considering homogeneous patches

        -   possible 'occupancy model' can lead to patches that are either vacant or occupied by populations at equilibrium when patches are identical

        -   regional coexistence can happen when species trade-offs exist between fitness/fecundity and dispersal

        -   dispersal can be constrained by predation and competition

        -   distinct time scales between local dynamics and regional 'colonization-extinction' dynamics

    -   Species-sorting (niche separation and coexistence) -

        -   built on theories of community change over environmental gradients, considering heterogeneous patches

        -   possible 'assembly model' where trade-offs among species lead to habitat specialization, where populations are at equilibrium behavior (stable point, oscillating, complex attractor) between colonization events and before extinctions caused by environmental perturbations

        -   local community compositions track changes in local environment (sharp or gradual) but maintain correspondence between local conditions and composition

        -   metacommunities can stabilize when local communities repeat assembly cycles as alternative states given sufficient heterogeneity among patches

        -   mass-effects are unlikely when immigration occurs at high levels but does not influence local communities, which will exhibit good correspondence between composition and conditions

    -   Mass-effects (density-dependent species interactions)

        -   built on probabilistic rules of population size and classical MacArthur consumer-resource model of species competition

        -   local population dynamics are quantitatively affected by dispersal, meaning no separation of time scales between local dynamics and competition-extinction dynamics

        -   introduces constraint of regional similarity, where coexisting species differ in ability to inhabit a patch type (MacArthur), but also compensating differences in abilities to compete and disperse make them similar at the regional scale

        -   metacommunity coexistence occurs via regional compensation, leading to species that are locally different but regionally similar (Amarasekare and Nisbet 2001)

While nearshore fish research in Alaska has been built over multiple decades, the information available in the literature lacks cohesion in terms of data analyses, ecological interpretation, and future outlook at the community level. In the last decade, other branches of ecology have led the way in performing analyses from a community perspective (e.g., multivariate inference models, joint species distributions, variable reduction). Some of these methods have already been applied to Alaskan nearshore fish communities, namely ordination and ANOVA based approaches. However, broad-scale analyses are still a gap considering the breadth of available datasets in both time and space compared to what has been done in other parts of the world. My dissertation aims to develop a cohesive understanding of nearshore fish community variability at the local-to-system scale, as well as at the region-to-region scale, and to examine if and how communities have changed over longer time periods. In my opinion, these are requisite analyses that will result in useful outcomes for fisheries management and ecosystem models, and will lead to next step analyses like those found in other branches of ecology.

# Proposed chapters

For chapter 1, I ask which physicochemical parameters and habitat factors structure nearshore fish communities within a system. Namely, I examine variance partitioned among temperature, salinity, turbidity, bay location, and site exposure (protected vs exposed) measured as water velocity. The goal of this chapter is to build upon existing knowledge of a well-studied system, and further understanding of within-system influences on community structuring.

-   

For chapter 2, I ask how nearshore fish communities are structured at varying spatial scales. In this chapter I expand the scale of study to include samples spread across multiple systems, first examining spatial autocorrelation and then parsing community variance among grouped samples (site-to-system-to-regional scales) with coastal habitat classes (ShoreZone) that are spatially heterogeneous. The goal of this chapter is to uilize the range of data available in Alaska (namely the Gulf of Alaska) to reveal appropriate spatial scales of fish community structuring then see at which scales nearshore habitat features can explain apparent structuring.

-   @Viana.etal.2022

-   @Dray.etal.2012

-   metacommunity, multiscale spatial analysis

For chapter 3, I ask if and how nearshore fish communities have changed over long-term periods (years-to-decades) coinciding with known climate-related trends. Specifically, I look for trends in community structure surrounding the marine heatwave that affected the Gulf of Alaska from 2014-2016. Results from chapter 2 should allow me to better account for spatial covariability, which will help me to interpret any temporal patterns. The goal of this chapter is to add to the current discourse in recent nearshore fish research from AK, which has related various fisherise data with temperature anomaly patterns, then discuss my findings in the context of nursery functions and hypothesize potential processes that could be at work.

-   @vonBiela.etal.2016

-   @Thorson.etal.2021

-   Climate change, Marine Heatwaves

-   Dynamic Factor Analysis

Chapter 4 - Size chapter. See @Ono.etal.2018 for roadmap, also check out @Thompson.etal.2019, @McGowan.etal.2020

# Approach

An early review of initial nearshore fish community assessments described a variety of gear types utilized, including trawls, seines, passive nets (e.g., gill, try, fyke), hook-and-line, and SCUBA. Each gear type resulted in different community assemblages, but seining methods typically produce the lowest selectivity. Beach seines specifically target shallow inshore waters usually \<5 m [method details in @Domke.etal.2024], and efficiently capture post-settlement juveniles - e.g., after larval transport in gadids and flatfish, or during outmigration in salmonids. In chapter 1, I collect new data in the study area of Kachemak Bay which represents a relatively well-studied system in terms of historical community assessments and published findings. This will provide me with a firm grasp of the sampling method, which will allow for a better understanding of how samples should be treated in data preparation and analyses. In chapters 2 and 3, I leverage the NOAA Nearshore Fish Atlas of Alaska database which aggregates data from numerous studies (\~20) conducted over multiple years (ca. 1990s to present). I will subset the NFAA and perform data preparations to fit the research question in either chapter. Although, I expect to focus on data collected from the GOA broadly (from SEAK to Aleutian Islands) due to the density of data on hand, as well as existing broad-scale ecosystem definitions (e.g., east vs west GOA) that can be tested using nearshore fish data which would be novel.

@Thedinga.etal.2008 Kruskal-Wallis ANOVA to test different habitat types followed by pairwise Dunn's method (Dunn 1964). Then catch log-transformed for box-whisker plots. 4th root transformed prior to Bray-Curtis dissimilarities, which was used for ANOSIM to find differences in composition among habitats, then for SIMPER to determine which species contributed to habitat groupings.

@Thedinga.etal.2013 mostly used log-transformed abundance and freq occur to compare samples, but also ranked bray-curtis on CPUE for ANOSIM (Clarke 1993) among sampling periods - testing if between-group dissimilarities are greater than within-group dissimilarity

@Konar.etal.2015 4th-root transformed abundances then Bray-Curtis distances, env vars checked for mv normality with bivariate draftsman plots, sq-root transformed and normalized, then euclidean distances. PERMANOVA test of regional differences: fish \~ region + (1 \| region/island), test of habitat differences: fish \~ region + habitat + (1 \| region/island). Species relative importance using SIMPER. Selection of best correlating env vars with BIOENV.

@Priest.etal.2022

@Laske.etal.2024

@Barton.etal.2020

# References
